export const movies = [
  {
    id: 1,
    title: "Interstellar",
    year: 2014,
    category: "Sci-Fi",
    description: "A team of explorers travel through a wormhole in space.",
    rating: 5,
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSngBJ0B7UDrLUkDlp6DCQLsEYuWR-DiHwbnxFFCniB3HiP3f3NZmR1-lKSC34ge6YXu4LX",
  },
  {
    id: 2,
    title: "The Dark Knight",
    year: 2008,
    category: "Action",
    description: "Batman faces the Joker in Gotham City.",
    rating: 5,
    poster: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTfE_qrYMBZ_JB8om-34WGaZARhpX26yWRttqIDvn4_7l--UzX8mxKcPrc59IcvTpEA_G8gPA",
  },
  {
    id: 3,
    title: "Inception",
    year: 2010,
    category: "Thriller",
    description: "A thief who steals corporate secrets through dreams.",
    rating: 4,
    poster: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRRyuWmayVBvqjd1MxTKpRgauq2cCtUzb7Q9QvaFTkAuxAU_EYMoCE3wBuJeftxIzf0grreIw",
  },
  {
    id: 4,
    title: "Jai Bhim",
    year: 2021,
    category: "Drama",
    description: "A lawyer fights for justice for tribal people.",
    rating: 4,
    poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFbXxEfLTuFL6-r184rnD_o3DzqThzc7naXvOXVLbG6gHyN1Td3CU9hZEi9JjlEiF4G75gSw",
  },
  {
    id: 5,
    title: "96",
    year: 2018,
    category: "Romance",
    description: "Two high school sweethearts meet after 22 years.",
    rating: 5,
    poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTJi8r3p1ofcc8GwLAjqrENm2YYAOTGOHSnc7jV9UMtSpR1k12D",
  },
  {
    id: 6,
    title: "Vikram",
    year: 2022,
    category: "Action",
    description: "A black ops squad is on a mission to bust drug lords.",
    rating: 4,
    poster: "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQVn0y7RuNHnktmebSF6Uf_bv6Ue5ZxMmrRR1I_Yz9Bvs51_P1AMV5ku8qB98PmOVTFK_oh",
  },
];
